
version: "3.9"

services:

  postgres:
    image: postgres:18
    container_name: guestregister-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: guest_register

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U application"]
      interval: 10s
      timeout: 5s
      retries: 5


  guestregister:

    build:
      context: .
      dockerfile: Dockerfile

    container_name: guestregister-app

    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:

      SPRING_PROFILES_ACTIVE: prod

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/guest_register
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./logs:/app/logs


volumes:
  pgdata: